service: noc-nse-scheduler

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-south-1
  profile: monocrome
  timeout: 30
  environment:
    DB_HOST: noc-nse.ct226m20ewfo.ap-south-1.rds.amazonaws.com
    DB_USERNAME: postgres
    DB_PASSWORD: TsHFHHVeufBwZdILTUml
    DB_NAME: postgres
    DB_PORT: 5432

functions:
  scheduler:
    handler: src/handler.runJob
    timeout: 260
    events:
      - schedule:
          rate: cron(0 15 * * ? *) # 8:30 PM IST (15:00 UTC)

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    target: node18
    platform: node
    sourcemap: true
    tsconfig: "./tsconfig.json"
